# Site settings
title: Hybrid | Dispatches from the Furry Experience
email: makyo@drab-makyo.com
description: >
  Hybrid is a nonfiction and poetry publication, highlighting
  what it means to be a furry in the modern subcommunity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hybrid.ink" # the base hostname & protocol for your site
twitter_username: hybrid_ink
permalink: pretty

# Build settings
markdown: kramdown
