# Site settings
title: Hybrid | Recognizing Excellence in Furry Non-fiction
email: hybrid@adjectivespecies.com
description: >
  Hybrid is an award recognizing excellence in furry nonfiction across all media.
brand: '<span class="brand">Hybrid</span>'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hybrid.ink" # the base hostname & protocol for your site
twitter_username: hybrid_ink
permalink: pretty

# Build settings
markdown: kramdown
