# Site settings
title: Hybrid | Independent publishers of thoughtful writing
email: hybrid@adjectivespecies.com
description: >
  Hybrid Ink is a small publisher focused on thoughtful fiction and creative non-fiction.
brand: '<span class="brand upper">Hybrid</span>'
name: '<span class="brand"><span class="upper">Hybrid</span> Ink</span>'
company: '<span class="brand"><span class="upper">Hybrid</span> Ink, Ltd</span>'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hybrid.ink" # the base hostname & protocol for your site
twitter_username: hybrid_ink
permalink: pretty

# Build settings
markdown: kramdown
